### ISSUE TITLE
Some jar files are not removed when upgrading from LSC 2.1 to 2.2

### ISSUE THREAD

**Issue by coudot** [lsc-project/lsc#504]
We upgraded LSC from 2.1.6 to 2.2.2 and we use LSC FD plugin 1.2.

We face this error:
```
mai 20 13:12:14 - ERROR - Error while getting pivot list (jakarta.ws.rs.ProcessingException: Class com.fasterxml.jackson.databind.util.LRUMap does not implement the requested interface com.fasterxml.jackson.databind.util.LookupCache)
mai 20 13:12:14 - DEBUG - jakarta.ws.rs.ProcessingException: Class com.fasterxml.jackson.databind.util.LRUMap does not implement the requested interface com.fasterxml.jackson.databind.util.LookupCache
jakarta.ws.rs.ProcessingException: Class com.fasterxml.jackson.databind.util.LRUMap does not implement the requested interface com.fasterxml.jackson.databind.util.LookupCache
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:312)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:671)
        at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:706)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:700)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:391)
        at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:700)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:670)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:436)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:342)
        at org.lsc.plugins.connectors.fusiondirectory.FusionDirectoryDao.startSession(FusionDirectoryDao.java:145)
        at org.lsc.plugins.connectors.fusiondirectory.FusionDirectoryDao.getToken(FusionDirectoryDao.java:190)
        at org.lsc.plugins.connectors.fusiondirectory.FusionDirectoryDao.httpGet(FusionDirectoryDao.java:202)
        at org.lsc.plugins.connectors.fusiondirectory.FusionDirectoryDao.httpGet(FusionDirectoryDao.java:198)
        at org.lsc.plugins.connectors.fusiondirectory.FusionDirectoryDao.getList(FusionDirectoryDao.java:319)
        at org.lsc.plugins.connectors.fusiondirectory.FusionDirectoryAbstractService.getList(FusionDirectoryAbstractService.java:64)
        at org.lsc.plugins.connectors.fusiondirectory.FusionDirectoryAbstractService.getList(FusionDirectoryAbstractService.java:60)
        at org.lsc.plugins.connectors.fusiondirectory.FusionDirectoryAbstractService.getListPivots(FusionDirectoryAbstractService.java:52)
        at org.lsc.AbstractSynchronize.synchronize2Ldap(AbstractSynchronize.java:208)
        at org.lsc.SimpleSynchronize.launchTask(SimpleSynchronize.java:334)
        at org.lsc.SimpleSynchronize.processTask(SimpleSynchronize.java:168)
        at org.lsc.SimpleSynchronize.processTasks(SimpleSynchronize.java:251)
        at org.lsc.SimpleSynchronize.launch(SimpleSynchronize.java:290)
        at org.lsc.Launcher.run(Launcher.java:208)
        at org.lsc.Launcher.launch(Launcher.java:153)
        at org.lsc.Launcher.main(Launcher.java:137)
```

We solved this by manually removing the following libs:
* jackson-annotations-2.10.1.jar
* jackson-core-2.10.1.jar
* jackson-databind-2.10.1.jar
* javax.ws.rs-api-2.1.1.jar

**Comment by davidcoutadeur** [comment]
giving a look at this.

There has been some work done on fd plugin. Also check that the new PR of fd-plugins are compatible.

**Comment by davidcoutadeur** [comment]
I can't reproduce the bug, nor find any version of jackson-annotations in lsc deb packages prior 2.2

Here are my findings about jackson-annotations in deb packages:

```
lsc-executable-plugin_1.0-1_all.deb
lsc-executable-plugin_1.1-1_all.deb
lsc-executable-plugin_1.2-1_all.deb
lsc-executable-plugin_1.3-1_all.deb
lsc-nis-plugin_1.0-1_all.deb
lsc-obm-plugin_1.2-1_all.deb
lsc-obm-plugin_1.3-1_all.deb
lsc-obm-plugin_1.4-1_all.deb
lsc_2.1.0-1_all.deb
lsc_2.1.1-1_all.deb
lsc_2.1.2-1_all.deb
lsc_2.1.3-1_all.deb
lsc_2.1.4-1_all.deb
lsc_2.1.5-1_all.deb
lsc_2.1.6-1_all.deb
lsc_2.2-1_all.deb
-rw-r--r-- root/root     78494 2025-04-11 11:00 ./usr/lib/lsc/jackson-annotations-2.18.2.jar
lsc_2.2.1-1_all.deb
-rw-r--r-- root/root     78494 2025-06-09 11:00 ./usr/lib/lsc/jackson-annotations-2.18.2.jar
lsc_2.2.2-1_all.deb
-rw-r--r-- root/root     78494 2026-01-05 11:00 ./usr/lib/lsc/jackson-annotations-2.18.2.jar
nagios-plugins-lsc_2.2-1_all.deb
nagios-plugins-lsc_2.2.1-1_all.deb
nagios-plugins-lsc_2.2.2-1_all.deb
```

as shown above, jackson-annotations appeared in lsc 2.2.

I suppose this is specific to the customer's installation, so we can just close the issue.
