### PR TITLE
Fix NoClassDefFoundError (com.sleepycat.je.DatabaseException) in sample LDAP server

### LINKED ISSUE #560: LSC quickstart not working in 2.3: Exception in thread "main" java.lang.NoClassDefFoundError: com/sleepycat/je/DatabaseException
I tried to run the quickstart with LSC 2.3: https://lsc-project.org/documentation/latest/quickstart.html

When launching the sample LDAP directory, I get this error:
```
bin/lsc-sample --start-ldap-server
Starting LDAP server on ldap://localhost:33389/ ...
août 21 11:59:33 - INFO  - Logging configuration successfully loaded from /home/clement/dev/lsc/lsc/target/lsc-core-2.4-SNAPSHOT-dist/lsc-2.4-SNAPSHOT/sample/hsqldb/bin/../etc/logback.xml 
août 21 11:59:33 - INFO  - LSC configuration successfully loaded from /home/clement/dev/lsc/lsc/target/lsc-core-2.4-SNAPSHOT-dist/lsc-2.4-SNAPSHOT/sample/hsqldb/bin/../etc/
Exception in thread "main" java.lang.NoClassDefFoundError: com/sleepycat/je/DatabaseException
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:536)
        at java.base/java.lang.Class.forName(Class.java:515)
        at org.opends.server.core.DirectoryServer.loadClass(DirectoryServer.java:9756)
        at org.opends.server.core.BackendConfigManager.initializeBackendConfig(BackendConfigManager.java:196)
        at org.opends.server.core.DirectoryServer.initializeBackends(DirectoryServer.java:2210)
        at org.opends.server.core.DirectoryServer.startServer(DirectoryServer.java:1397)
        at org.lsc.opendj.EmbeddedOpenDJ.startServer(EmbeddedOpenDJ.java:160)
        at org.lsc.opendj.LdapServer.start(LdapServer.java:81)
        at org.lsc.opendj.LdapServer.usage(LdapServer.java:181)
        at org.lsc.opendj.LdapServer.main(LdapServer.java:123)
Caused by: java.lang.ClassNotFoundException: com.sleepycat.je.DatabaseException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 11 more

### PR DESCRIPTION
**Pull request by Kcchouette**
### Summary

Fixes `java.lang.NoClassDefFoundError: com/sleepycat/je/DatabaseException` when starting the embedded OpenDJ LDAP server using `bin/lsc-sample --start-ldap-server`.

### Root Cause

- OpenDJ 2.6.4 relies on Berkeley DB Java Edition (`org.opends.server.backends.jeb.BackendImpl`) for its `userRoot` local storage backend.
- The `opendj-server:2.6.4` Maven artifact was published without transitive runtime dependencies, omitting `com.sleepycat:je`.
- Consequently, the Sleepycat JE library was missing from both the runtime classpath and the distribution archive `sample/lib` directory.

### Changes

1. **`pom.xml`**: Added explicit dependency `com.sleepycat:je:5.0.73` under Sleepycat License (BSD-compatible).
2. **`src/main/assembly/dist.xml`**: Fixed OpenDJ `groupId` to `org.forgerock.ce.opendj` and routed `com.sleepycat:je` to `sample/lib`.
3. **`sample/*/bin/lsc-sample`**:
   - Added `sample/lib/*.jar` to the sample script classpath (`LDAPCP`).
   - Added required JVM `--add-opens` flags for Java 17/21 compatibility.
   - Fixed a bash syntax typo in `sample/ldap2hsqldb/bin/lsc-sample`.

Related to https://github.com/lsc-project/lsc/issues/560

### CODE REVIEW

**Comment by coudot** [comment]
Thanks, the quickstart is working now!
